### ISSUE TITLE
Should throw informational exception when client is not found when getClientByAccountNumber() is invoked

### ISSUE THREAD

**Issue by pitzzahh** [pitzzahh/automated-teller-machine-API#14]
When the client is not found, it throws 
```java
Exception in thread "main" org.springframework.dao.EmptyResultDataAccessException: Incorrect result size: expected 1, actual 0
	at org.springframework.dao.support.DataAccessUtils.nullableSingleResult(DataAccessUtils.java:97)
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:887)
	at io.github.pitzzahh.atm.dao.AtmDAOImplementation.lambda$getClientByAccountNumber$3(AtmDAOImplementation.java:81)
	at App.main(App.java:47)
```
which is valid but not much info about it.

**Comment by pitzzahh** [comment]
fixed on commit: https://github.com/pitzzahh/automated-teller-machine-API/commit/9413d688abd30d1367443465219ef1658ba7f5e4
